# You can override the included template(s) by including variable overrides
# See https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#priority-of-environment-variables
stages:
- build
- test
- analyze
- deploy

.sourcechanged:
  rules:
    - changes:
      - api/*
      - ./*.js
      - config/*.js
      - controllers/*.js
      - models/*.js
      - service/*.js
      - static/
      - subscribers/*.js
      - utils/*.js

image: node:14
cache:
  paths:
  - node_modules/
variables:
  versionTag: "$CI_COMMIT_SHA"
  NEXUS_URL: "https://nexus.myocastor.de/repository/bintra_rpm/"

makedocs:
  stage: build
  image: "$CI_REGISTRY/kai/lggr:mkdocs"
  before_script:
  - mkdir pub_mkdocs
  script:
  - mkdocs build
  artifacts:
    paths:
    - pub_mkdocs

jsdocs:
  stage: build
  before_script:
  - npm install
  script:
  - "./node_modules/.bin/jsdoc --verbose -c jsdoc.json"
  artifacts:
    paths:
    - out

unittest:
  extends: .sourcechanged
  stage: test
  image: "$CI_REGISTRY/kai/bintra:fat"
  variables:
    NODE_ENV: test
  before_script:
  - "/etc/init.d/mongodb start"
  - npm install
  - "./setup_env_test.sh"
  script:
  - npm run combined
  coverage: "/Statements\\s+:\\s+(\\d+\\.\\d+)%/"
  artifacts:
    paths:
    - mochawesome-report/
    - coverage/
    - xunit.xml

sonarqube:
  extends: .sourcechanged
  stage: analyze
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint:
    - ''
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  before_script:
  - git fetch --unshallow
  script:
  - sonar-scanner -Dsonar.qualitygate.wait=true -Dsonar.branch.name=${CI_COMMIT_REF_SLUG}
  allow_failure: false

pages:
  extends: .sourcechanged
  stage: deploy
  image: alpine
  before_script:
  - mkdir public
  - mkdir public/jsdoc
  - mkdir public/mocha
  script:
  - cp -a pub_mkdocs/* public/
  - cp -a out/* public/jsdoc/
  - cp -a mochawesome-report/* public/mocha/
  artifacts:
    paths:
    - public

debDebian:
  stage: deploy
  image: "$CI_REGISTRY/kai/bintra:deb"
  script:
  - cd client && chmod -R 644 . && find . -type d -exec chmod 755 {} \; && chmod 755
    bintra/usr/sbin/bintra && dpkg-deb --root-owner-group --build bintra
  artifacts:
    paths:
    - client/bintra.deb
  only:
    refs:
    - master

rpmFedora:
  stage: deploy
  image: fedora:34
  before_script:
  - dnf -y -q update
  - dnf -y -q install git rpm-build rpmdevtools rpm-sign
  script:
  - rpmdev-setuptree
  - cd ~/rpmbuild
  - cp /builds/kai/bintra/client/dnf/bintra.spec SPECS/
  - rpmbuild -bb SPECS/bintra.spec
  - 'curl -v -i --user ${NEXUS_USER}:${NESUS_PASSWD} --upload-file `find RPMS/ -type f` ${NEXUS_URL}'
#  artifacts:
#    paths:
#    - /root/rpmbuild/RPMS/noarch/
  only:
    refs:
    - master

rpmCentos:
  stage: deploy
  image: centos:8
  before_script:
  - dnf -y -q update
  - dnf -y -q install git curl rpm-build rpmdevtools rpm-sign
  script:
  - rpmdev-setuptree
  - cd ~/rpmbuild
  - cp /builds/kai/bintra/client/dnf/bintra.spec SPECS/
  - rpmbuild -bb SPECS/bintra.spec
  - 'curl -v -i --user ${NEXUS_USER}:${NESUS_PASSWD} --upload-file `find RPMS/ -type f` ${NEXUS_URL}'
#  artifacts:
#    paths:
#    - /root/rpmbuild/RPMS/noarch/
  only:
    refs:
    - master

publish:
  stage: deploy
  image: ubuntu:latest
  variables:
    GIT_STRATEGY: none
  cache: {}
  dependencies: []
  before_script:
  - which ssh-agent || ( apt-get update -y && apt-get install -y -qq openssh-client
    )
  - mkdir -p ~/.ssh
  - chmod 0700 ~/.ssh
  - eval $(ssh-agent -s)
  - echo "$SSH_CI_PRIV" | tr -d '\r' | ssh-add -
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
  - ssh ansi@ctl.myocastor.de "cd playbooks && ansible-playbook apiupdate.yml"
  only:
  - master

sast:
  extends: .sourcechanged
  stage: analyze
include:
- template: Security/SAST.gitlab-ci.yml
- template: Security/Secret-Detection.gitlab-ci.yml
.secret-analyzer:
  extends: .sourcechanged
  stage: analyze
