include:
  - local: workflows/compile.yml
    rules:
      - if: $CI_COMMIT_TAG
        when: never
  - local: workflows/publish.yml
    rules:
      - if: $CI_COMMIT_TAG
  - local: workflows/merge.yml
    rules:
      - if: $CI_MERGE_REQUEST_IID
      - if: $CI_COMMIT_TAG
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
