stages:
  - build
  - test
  - report
  - analyze
  - deploy

include:
  - local: 'workflows/empty.yml'

#  - local: 'workflows/original.yml'

  - local: 'workflows/compile.yml'
    rules:
      - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG == null'

  - local: 'workflows/merge.yml'
    rules:
      - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

  - local: 'workflows/publish.yml'
    rules:
      - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG != null'
