---
version: '3'

services:
  database:
    image: mongo:latest
    container_name: 'bintra-mongo'
    restart: unless-stopped
    env_file: .env.docker
    environment:
      - MONGO_INITDB_DATABASE=bintra
    volumes:
      - dbdata:/data/db
    networks:
      - bintra-network
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/bintra --quiet
      interval: 5s
      timeout: 5s
      retries: 12

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: 'bintra-nodejs'
    restart: unless-stopped
    depends_on:
      - database
    env_file: .env.docker
    environment:
      - NODE_ENV=docker
      - MONGO_HOSTNAME=database
    ports:
      - "8087:8080"
    networks:
      - bintra-network
    command: npm start
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080/docs/"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  bintra-network:
    driver: bridge

volumes:
  dbdata:
