version: '3'

services:
  database:
    image: mongo:latest
    container_name: 'bintra-mongo'
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_DATABASE=$MONGO_DB
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
            #      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - dbdata:/data/db
    networks:
      - bintra-network

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: 'bintra-nodejs'
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=database
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - "80:8080"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - bintra-network

networks:
  bintra-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
